B1

In [ ]:
import numpy as np

# Define vectors A and B
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])

# Calculate A + B
sum_AB = A + B
print(f"a) A + B = {sum_AB}")

# Calculate 3A - 2B
result_3A_2B = 3 * A - 2 * B
print(f"   3A - 2B = {result_3A_2B}")

a) A + B = [3 3 1 5]
   3A - 2B = [  4 -11  13 -10]


In [ ]:
import numpy as np

A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])

# Calculate dot product A . B
dot_product_AB = np.dot(A, B)
print(f"b) Tích vô hướng A . B = {dot_product_AB}")

# Calculate magnitudes (norms) of A and B
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)

# Calculate cosine of the angle
if norm_A * norm_B != 0:
    cos_theta = dot_product_AB / (norm_A * norm_B)
    print(f"   cos(theta) = {cos_theta:.6f}") # Print with more precision for checking

    # Calculate angle in radians and then convert to degrees
    theta_radians = np.arccos(np.clip(cos_theta, -1.0, 1.0)) # Clip to handle potential floating point inaccuracies
    theta_degrees = np.degrees(theta_radians)
    print(f"   Góc giữa hai vector (độ) = {theta_degrees:.3f} độ")
else:
    print("   Không thể tính góc vì ít nhất một vector có độ dài bằng 0.")

b) Tích vô hướng A . B = -8
   cos(theta) = -0.315244
   Góc giữa hai vector (độ) = 108.376 độ


In [ ]:
import numpy as np

# Define matrix C
C = np.array([[1, 2],
              [-1, 0],
              [3, -1],
              [2, -1]])

# Calculate the transpose of C
C_transpose = C.T
print("c) Ma trận C^T:\n", C_transpose)

# Calculate the product C^T * C
product_CTC = np.dot(C_transpose, C)
print("   Tích ma trận C^T * C:\n", product_CTC)

c) Ma trận C^T:
 [[ 1 -1  3  2]
 [ 2  0 -1 -1]]
   Tích ma trận C^T * C:
 [[15 -3]
 [-3  6]]


B2

In [ ]:
import numpy as np

# Define matrices M and N
M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 0],
              [0, 1, 1, 0]])

N = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11],
              [12, 13, 14, 15]])

# Calculate M * N
product_MN = np.dot(M, N)
print(f"a) Tích ma trận M * N:\n{product_MN}")

# Calculate M * N - N
result_MN_minus_N = product_MN - N
print(f"   Kết quả M * N - N:\n{result_MN_minus_N}")

a) Tích ma trận M * N:
[[ 32  38  44  50]
 [ 80  96 112 128]
 [104 128 152 176]
 [ 12  14  16  18]]
   Kết quả M * N - N:
[[ 32  37  42  47]
 [ 76  91 106 121]
 [ 96 119 142 165]
 [  0   1   2   3]]


In [ ]:
import numpy as np

M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 0],
              [0, 1, 1, 0]])

# Calculate the determinant of M
det_M = np.linalg.det(M)
print(f"b) Định thức của ma trận M = {det_M:.6f}")

# Check if M is invertible
if det_M != 0:
    print("   Ma trận M khả nghịch vì định thức của nó khác 0.")
else:
    print("   Ma trận M không khả nghịch vì định thức của nó bằng 0.")

b) Định thức của ma trận M = 6.000000
   Ma trận M khả nghịch vì định thức của nó khác 0.


In [ ]:
import numpy as np

M = np.array([[1, 2, 3, 0],
              [4, 5, 6, 1],
              [7, 8, 9, 0],
              [0, 1, 1, 0]])

# Calculate the rank of M
rank_M = np.linalg.matrix_rank(M)
print(f"c) Hạng của ma trận M = {rank_M}")

c) Hạng của ma trận M = 4


B3

In [ ]:
import numpy as np

# Dữ liệu từ đề bài Câu 3
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])

b = np.array([3, 7, 9, 5])

print("--- Lời giải cho Câu 3 ---")

# a) Tìm ma trận nghịch đảo của P
det_P = np.linalg.det(P)
print(f"a) Định thức của P là: {det_P:.2f}")

if det_P != 0:
    P_inv = np.linalg.inv(P)
    print("Ma trận P khả nghịch. Ma trận nghịch đảo P⁻¹ là:")
    print(np.round(P_inv, 3))
else:
    print("Ma trận P không khả nghịch.")

# b) Giải hệ phương trình bằng ma trận nghịch đảo
x = P_inv @ b
print("\nb) Nghiệm của hệ phương trình (x, y, z, w) là:")
print(np.round(x, 3))

# c) Kiểm tra lại nghiệm
verification = P @ x
print("\nc) Kiểm tra lại nghiệm (P * x):")
print(np.round(verification, 3))
print("Vector hằng số b ban đầu:")
print(b)

if np.allclose(verification, b):
    print("=> Kết quả kiểm tra chính xác!")
else:
    print("=> Kết quả kiểm tra có sai lệch.")

B4

In [ ]:
import numpy as np

Q_corrected = np.array([
    [1, -1, 0],
    [-1, 2, 1],
    [0, 1, 1]
])

print("\n--- Lời giải cho Câu 4 (với ma trận đã sửa) ---")
print("Ma trận Q (đã sửa) được sử dụng:")
print(Q_corrected)

# a) Tìm các giá trị riêng
# b) Tìm các vector riêng
# Hàm np.linalg.eig sẽ tính cả hai cùng lúc.
# eigenvalues là một mảng các giá trị riêng.
# eigenvectors là một ma trận với mỗi cột là một vector riêng tương ứng.
eigenvalues, eigenvectors = np.linalg.eig(Q_corrected)

print("\na) Các giá trị riêng (eigenvalues) là:")
print(np.round(eigenvalues, 3))

print("\nb) Các vector riêng (eigenvectors) tương ứng (mỗi cột là một vector):")
print(np.round(eigenvectors, 3))

# c) Chuẩn hóa tất cả các vector riêng
print("\nc) Các vector riêng đã được chuẩn hóa (độ dài bằng 1):")
for i in range(len(eigenvectors)):
    vector = eigenvectors[:, i]
    # np.linalg.norm tính độ dài (chuẩn L2) của vector
    normalized_vector = vector / np.linalg.norm(vector)
    print(f"Vector chuẩn hóa cho λ = {eigenvalues[i]:.2f}:")
    print(np.round(normalized_vector, 3))
    print("-" * 15)


--- Lời giải cho Câu 4 (với ma trận đã sửa) ---
Ma trận Q (đã sửa) được sử dụng:
[[ 1 -1  0]
 [-1  2  1]
 [ 0  1  1]]

a) Các giá trị riêng (eigenvalues) là:
[ 3.  1. -0.]

b) Các vector riêng (eigenvectors) tương ứng (mỗi cột là một vector):
[[-0.408 -0.707 -0.577]
 [ 0.816  0.    -0.577]
 [ 0.408 -0.707  0.577]]

c) Các vector riêng đã được chuẩn hóa (độ dài bằng 1):
Vector chuẩn hóa cho λ = 3.00:
[-0.408  0.816  0.408]
---------------
Vector chuẩn hóa cho λ = 1.00:
[-0.707  0.    -0.707]
---------------
Vector chuẩn hóa cho λ = -0.00:
[-0.577 -0.577  0.577]
---------------


B5

In [ ]:
import numpy as np

# Dữ liệu từ đề bài Câu 5
R = np.array([
    [1, -2, 0],
    [2, 0, 1],
    [1, 1, -1]
])

h = np.array([10, 8, 7])

print("\n--- Lời giải cho Câu 5 ---")

# a) Giải hệ phương trình Rx = h bằng linalg.solve()
print("a) Giải hệ phương trình bằng linalg.solve():")
x_solve = np.linalg.solve(R, h)
print("Nghiệm của hệ (x, y, z) là:")
print(np.round(x_solve, 3))

# b) Kiểm tra tính khả nghịch, tìm ma trận nghịch đảo và giải lại
print("\nb) Kiểm tra và giải lại bằng ma trận nghịch đảo:")
det_R = np.linalg.det(R)
print(f"Định thức của R là: {det_R:.2f}")

if det_R != 0:
    print("Ma trận R khả nghịch.")
    # Tìm ma trận nghịch đảo
    R_inv = np.linalg.inv(R)
    print("Ma trận nghịch đảo R⁻¹ là:")
    print(np.round(R_inv, 3))

    # Giải lại hệ phương trình: x = R⁻¹ * h
    x_inv = R_inv @ h
    print("\nNghiệm tìm được bằng ma trận nghịch đảo:")
    print(np.round(x_inv, 3))

    # So sánh kết quả
    if np.allclose(x_solve, x_inv):
        print("=> Hai phương pháp cho ra cùng một kết quả.")
    else:
        print("=> Hai phương pháp cho ra kết quả khác nhau.")
else:
    print("Ma trận R không khả nghịch.")

# c) Tính chuẩn Frobenius của ma trận R
# Chuẩn Frobenius là căn bậc hai của tổng bình phương tất cả các phần tử.
frobenius_norm = np.linalg.norm(R, 'fro')
print(f"\nc) Chuẩn Frobenius của ma trận R là: {frobenius_norm:.3f}")


--- Lời giải cho Câu 5 ---
a) Giải hệ phương trình bằng linalg.solve():
Nghiệm của hệ (x, y, z) là:
[ 5.714 -2.143 -3.429]

b) Kiểm tra và giải lại bằng ma trận nghịch đảo:
Định thức của R là: -7.00
Ma trận R khả nghịch.
Ma trận nghịch đảo R⁻¹ là:
[[ 0.143  0.286  0.286]
 [-0.429  0.143  0.143]
 [-0.286  0.429 -0.571]]

Nghiệm tìm được bằng ma trận nghịch đảo:
[ 5.714 -2.143 -3.429]
=> Hai phương pháp cho ra cùng một kết quả.

c) Chuẩn Frobenius của ma trận R là: 3.606
