# BAI TAP

In [ ]:
def scale(a, v):
 return [a*vi for vi in v]
v = [3,5,7]
scale(10, v)

[30, 50, 70]

In [ ]:
def sumvector(v, w):
 return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
sumvector(v, w)

[5, 9, 13]

In [ ]:
def dotvector(v, w):
  return sum([vi*wi for (vi, wi) in zip(v, w)])
dotvector(v, w)

68

In [ ]:
def lenvector(v):
 return dotvector(v,v)
lenvector(w)

56

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores

array([-1,  1,  2, -3,  5, -4])

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores >= 0


array([ True, False, False,  True, False,  True])

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores < 0

array([ True, False, False,  True, False,  True])

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
np.select([scores >=0, scores < 0],['so duong', 'so am'], default='khong xac dinh')

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U14')

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'], default='khong xac dinh')

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U14')

In [ ]:
import numpy as np
from scipy import linalg, sparse
D = np.asmatrix([ [3,4], [5,6] ])
print(D)
c = np.asmatrix(np.random.random((5,7)))
print(c)
A = np.asmatrix(np.random.random((2,2)))
print(A)
b = np.array([(1+5j, 2j, 3j),(4, 5,
6)])
B = np.asmatrix(b)
print(b)
print(B)
h = A.T
print(h)
g = A.I
print(g)
linalg.inv(A)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M) #vector đường chéo
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag)

[[3 4]
 [5 6]]
[[0.65946208 0.91169786 0.74100775 0.54221883 0.79882458 0.81934756
  0.860559  ]
 [0.26404568 0.54794896 0.31965662 0.17419942 0.28854568 0.62157364
  0.94062376]
 [0.63342778 0.30654399 0.63540003 0.35748653 0.33311054 0.71176089
  0.58337328]
 [0.65821834 0.14350683 0.77131098 0.23299772 0.21281078 0.23508185
  0.64114452]
 [0.68419036 0.07868993 0.22899518 0.49367872 0.44253734 0.19994791
  0.31241032]]
[[0.45533159 0.90237226]
 [0.91745113 0.81241206]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[0.45533159 0.91745113]
 [0.90237226 0.81241206]]
[[-1.7739588   1.97039321]
 [ 2.00331899 -0.99424851]]
[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]
[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]
[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [ ]:
import sympy as sp
x= sp.Symbol('x')
y= sp.Symbol('y')
z= sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x, y, z])


[(2, 7, -1)]

In [ ]:
import numpy as np

A = np.reshape(np.arange(36.0), (6,6))
print(A)
I6 = np.identity(6)
print(I6)
A.size
import numpy as np

A = np.reshape(np.arange(36.0), (6,6))
print(A)
I6 = np.identity(6)
print(I6)
A.size
np.matrix.diagonal(A)
A = A + I6
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [ ]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)
E = A.dot(D.T)
print(E)

[ 71. 198. 325. 452. 579. 706.]
[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [ ]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print(F)
print(G)
n = np.linalg.inv(A)
print(n)
f = np.linalg.inv(np.linalg.inv(A))
print(f)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]
[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [ ]:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10

for i in range(n):
    B = A.dot(b)
    print(B)

[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]
[1 1]


In [ ]:
import sympy as sp
from sympy import Symbol
17
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
import sympy as sp
from sympy import Symbol
17
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
nghiem

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

In [ ]:
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
determinant_A = np.linalg.det(A)
print(f"Determinant of A: {determinant_A}")

Determinant of A: 0.0


BAI TAP VE NHA

In [1]:
import numpy as np


a1 = 1
b1 = -1
c1 = -2


a2 = 2
b2 = 3
c2 = 6


A_prob1 = np.array([[a1, b1], [a2, b2]])


B_prob1 = np.array([c1, c2])


try:
    solution_prob1 = np.linalg.solve(A_prob1, B_prob1)
    x_prob1, y_prob1 = solution_prob1
    print(f"Vấn đề 1: Điểm giao nhau giữa hai đường thẳng là x = {x_prob1:.2f}, y = {y_prob1:.2f}")
except np.linalg.LinAlgError:
    print("Vấn đề 1: Hai đường thẳng song song hoặc trùng nhau (không có điểm giao duy nhất).")

Vấn đề 1: Điểm giao nhau giữa hai đường thẳng là x = 0.00, y = 2.00


In [2]:
import numpy as np

a1, b1, c1, d1 = 1, -1, -1, 2

a2, b2, c2, d2 = 2, -1, -1, 3

a3, b3, c3, d3 = 1, 1, 1, 6

A_prob2 = np.array([[a1, b1, c1], [a2, b2, c2], [a3, b3, c3]])

B_prob2 = np.array([d1, d2, d3])

try:
    solution_prob2 = np.linalg.solve(A_prob2, B_prob2)
    x_prob2, y_prob2, z_prob2 = solution_prob2
    print(f"Vấn đề 2: Điểm giao nhau giữa ba mặt phẳng là x = {x_prob2:.2f}, y = {y_prob2:.2f}, z = {z_prob2:.2f}")
except np.linalg.LinAlgError:
    print("Vấn đề 2: Các mặt phẳng không giao nhau tại một điểm duy nhất (có thể song song, trùng nhau hoặc giao nhau tạo thành đường thẳng).")

Vấn đề 2: Các mặt phẳng không giao nhau tại một điểm duy nhất (có thể song song, trùng nhau hoặc giao nhau tạo thành đường thẳng).
