BAI TAP

In [ ]:
from scipy import linalg
import numpy as np

a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
C = np.asmatrix(np.random.random( (10,5) ) )
D = np.asmatrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1)
E = np.eye(3, k=0)
G = np.eye(3, k=-1)
np.linalg.matrix_rank(C)
A.I
linalg.inv(A)
linalg.det(A)
A.T
A.H
linalg.solve(A, b)
np.asmatrix(a).T
linalg.lstsq(F, E)
np.add(A, D)
np.subtract(A, D)
np.divide(A, D)
A @ D
np.multiply(D, A)
np.dot(A, D)
np.vdot(A, D)
linalg.expm(A)
print(a)
print(b)
print(c)
print(A)
print(B)
print(C)
print(D)
print(F)
print(E)
print(G)
print(np.linalg.matrix_rank(C) )
print(A.I)
print(linalg.inv(A))
print(linalg.det(A))
print(A.T)
print(A.H)
print(linalg.solve(A, b))
print(np.asmatrix(a).T)
print(linalg.lstsq(F, np.asmatrix(a).T))
print(np.add(A, D))
print(np.subtract(A, D))
print(np.divide(A, D))
print(A @ D)
print(np.multiply(D, A))
print(np.dot(A, D))
print(np.vdot(A, D))
print( linalg.expm(A) )
linalg.logm(A)
print( linalg.logm(A) )

[1 2 3]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[[ 0.5  1.5 10. ]
  [ 3.   2.   1. ]]

 [[ 6.   5.   4. ]
  [ 7.   8.   9. ]]]
[[0.36826793 0.31498648]
 [0.81401223 0.8375888 ]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.98313482 0.07125213 0.32966956 0.6631767  0.82159464]
 [0.11622027 0.4875436  0.81146025 0.18308188 0.89215284]
 [0.57311142 0.47723913 0.15370603 0.87156652 0.70489218]
 [0.76818446 0.36481271 0.63175464 0.07573621 0.99546937]
 [0.41033017 0.78517333 0.64338635 0.02372894 0.29092395]
 [0.05453452 0.75665568 0.10329294 0.2078575  0.38599341]
 [0.09780734 0.16319422 0.06909448 0.98907794 0.45924262]
 [0.59980038 0.85888867 0.31116517 0.74183622 0.72053149]
 [0.82982327 0.59401266 0.09883808 0.53115177 0.02542389]
 [0.54464109 0.5207158  0.43977284 0.77572486 0.69123174]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
5
[[ 16.09069145  -6.05111997]
 [-15.63776835   7.074695

In [ ]:
import numpy as np
A = np.array([ [0,1], [1,0]])
print(A)
temp = A.dot(A) # tính toan lần thứ 1
print(temp)
k= 6
for i in range(k-1):
 temp = temp.dot(A)
 print (temp)
 print('---')
B = np.array([ [0,-1], [-1,0]])
print(B)
temp = B.dot(B) # tính toan lần thứ 1
print(temp)
k= 5
for i in range(k-1):
 temp = temp.dot(B)
 print (temp)
 print('---')
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)
temp = C.dot(C)
print(temp)
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp)
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp)



[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)
MM = M.dot(M) # tính M3
print (MM)
for i in range(100): # tính các M^ khác.
 MM = MM.dot(M)
print (MM) # kết luận xu hướng của jb



[[0.7  0.45]
 [0.3  0.55]]
[[0.7  0.45]
 [0.3  0.55]]
[[0.6 0.6]
 [0.4 0.4]]


In [ ]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print (P)
print (L)
print (U)
L.dot(U)
print(L.dot(U) )


[[1. 0.]
 [0. 1.]]
[[1.   0.  ]
 [0.25 1.  ]]
[[0.8   0.3  ]
 [0.    0.625]]
[[0.8 0.3]
 [0.2 0.7]]


In [ ]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) # lúc này temp = õ
print(temp)
temp = temp.dot(A) # lúc này temp = õ
print(temp)
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
 temp = temp.dot(A)
 sumA = sumA + temp
print (temp)
print (sumA)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
