In [42]:
import numpy as np
n = 4
X = np.array(range(1,n+1))
sigma = np.array([4,3,2,1])
def sgn_by_def(sigma):
    ketqua = 1.0
    for i in range(len(X)-1):
      for j in range (i +1, len(X)):
        ketqua= ketqua * ((X[i]-X[j])/(sigma[i]-sigma[j]))
    return int (ketqua)
print(sgn_by_def(sigma))

1


In [43]:
import numpy as np
n = 4
X = np.array(range(1,n+1))
sigma = np.array([2,1,3,4])
def sgn_by_def(sigma):
    ketqua = 1.0
    for i in range(len(X)-1):
      for j in range (i +1, len(X)):
        ketqua= ketqua * ((X[i]-X[j])/(sigma[i]-sigma[j]))
    return int (ketqua)
print(sgn_by_def(sigma))

-1


In [44]:
import numpy as np
n = 4
X = np.array(range(1,n+1))
sigma = np.array([1,2,3,4])
def sgn_by_def(sigma):
    ketqua = 1.0
    for i in range(len(X)-1):
      for j in range (i +1, len(X)):
        ketqua= ketqua * ((X[i]-X[j])/(sigma[i]-sigma[j]))
    return int (ketqua)
print(sgn_by_def(sigma))

1


In [45]:
from itertools import permutations
n = 3
X = []
for i in range (1, n+1):
  X.append(i)
Sn = list(permutations(X)) #tạo hoán vị của tập X
print (Sn)

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [46]:
from itertools import permutations
import numpy as np
def sgn_by_def(sigma):
    n = len(sigma)
    inversions = 0
    for i in range(n):
        for j in range(i + 1, n):
            if sigma[i] > sigma[j]:
                inversions += 1
    return -1 if inversions % 2 else 1
def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = ""
        for i in range(1,n+1):
            sigma[sn.index(i)] = i
            product = product + "a" + str(i) + str(sn.index(i)+1)
        dau = sgn_by_def(sigma)
        if dau != 1:
            product = " - " + product
        else:
            product = " + " + product
        dinhthuc = dinhthuc + product
    return dinhthuc
# Gọi hàm với n = 2
print(phatsinh_dinhthuc(2))

 + a11a22 - a12a21


In [47]:
import numpy as np
from itertools import permutations

def sgn_by_def(sigma, n):
    X = np.array(range(1, n + 1))
    ketqua = 1.0
    for i in range(n - 1):
      for j in range (i + 1, n):
        ketqua= ketqua * ((X[i]-X[j])/(sigma[i]-sigma[j]))
    return int (ketqua)

def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        sigma = np.zeros(n, dtype=int)
        product = ""
        for i in range(1,n+1):
            sigma[sn.index(i)] = i
            product = product + "a" + str(i) + str(sn.index(i)+1)

        dau = sgn_by_def(sigma, n)
        if dau != 1:
            product = " - " + product
        else:
            product = " + " + product
        dinhthuc = dinhthuc + product
    return dinhthuc

print(phatsinh_dinhthuc(3))

 + a11a22a33 - a11a23a32 - a12a21a33 + a13a21a32 + a12a23a31 - a13a22a31


In [48]:
import numpy as np
from itertools import permutations
import math
def sgn_by_def(sigma):
    pass
def tinh_toan_dinh_thuc(A):
    X = []
    n = int(math.sqrt(A.size))
    for i in range(1, n + 1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1
        for i in range(1, n + 1):
            sigma[sn.index(i)] = i
            product *= A[i - 1][sn.index(i)]
        dau = sgn_by_def(sigma)
        if dau != 1:
            product *= -1
        dinhthuc += product
    return dinhthuc
matran = np.array([[3, 5, -8], [4, 12, -1], [2, 5, 3]])
ket_qua = tinh_toan_dinh_thuc(matran)
print("Định thức của ma trận là:", ket_qua)

Định thức của ma trận là: 209


In [49]:
import numpy as np
A = np.array([[4, -2],[3, -5]]) # khai báo ma trận A
A1 = np.array([[10, -2],[11, -5]])
A2 = np.array([[4, 10],[3, 11]])
from scipy import linalg # lưu ý: hàm tính định thức của ma trận là scipy.linalg.det(A)
detA = linalg.det(A) # tính định thức cho ma trận A
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
print (detA, detA1, detA2)
if (detA != 0):
 x1 = detA1 / detA
 x2 = detA2 / detA
 print ("Hai nghiệm của phương trình là: ", x1, x2)

-14.0 -28.0 14.000000000000004
Hai nghiệm của phương trình là:  2.0 -1.0000000000000002


In [50]:
from scipy import linalg
def tinhtoan_dinhthuc():
    A = [[4, -2], [3, -5]]
    A1 = [[10, -2], [11, -5]]
    A2 = [[4, 10], [3, 11]]
    detA = linalg.det(A)
    detA1 = linalg.det(A1)
    detA2 = linalg.det(A2)
    print(f"Định thức A: {detA}")
    print(f"Định thức A1: {detA1}")
    print(f"Định thức A2: {detA2}")
    if detA != 0:
        x1 = detA1 / detA
        x2 = detA2 / detA
        print(f"Nghiệm của hệ ptrình: x1 = {x1}, x2 = {x2}")
    else:
        print("Hệ ptrình vô nghiệm hoặc vô số nghiệm")
tinhtoan_dinhthuc()

Định thức A: -14.0
Định thức A1: -28.0
Định thức A2: 14.000000000000004
Nghiệm của hệ ptrình: x1 = 2.0, x2 = -1.0000000000000002


In [51]:
import numpy as np
from scipy.linalg import det
A = np.array([
    [-1, 2, -3],
    [2, -2, 1],
    [3, -4, 1]])
B = np.array([1, 3, 2])
D = det(A)
def tinhtoan_dinhthuc(A, B, index):
    A_copy = A.copy()
    A_copy[:, index] = B
    return det(A_copy)
Dx = tinhtoan_dinhthuc(A, B, 0)
Dy = tinhtoan_dinhthuc(A, B, 1)
Dz = tinhtoan_dinhthuc(A, B, 2)
x = Dx / D
y = Dy / D
z = Dz / D
print("Nghiệm của hệ phương trình là:")
print(f"x = {x}, y = {y}, z = {z}")

Nghiệm của hệ phương trình là:
x = 3.9999999999999996, y = 2.4999999999999996, z = 0.0


In [52]:
import numpy as np
from scipy.linalg import det
A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])
B = np.array([1, 3, 2])
dinh_thuc_A = det(A)
print(f"Định thức của ma trận hệ số (A) là: {dinh_thuc_A}")
if dinh_thuc_A != 0:
    nghiem = np.linalg.solve(A, B)
    print("Nghiệm của hệ ptrình là:")
    print(f"x = {nghiem[0]}, y = {nghiem[1]}, z = {nghiem[2]}")
else:
    print("Hệ ptrình không có nghiệm duy nhất")

Định thức của ma trận hệ số (A) là: 0.0
Hệ ptrình không có nghiệm duy nhất


In [53]:
def tinhtoan_dinhthuc(matrix):
    return np.linalg.det(matrix)
dinh_thuc_A_tu_viet = tinhtoan_dinhthuc(A)
print(f"Định thức của ma trận hệ số (A) là: {dinh_thuc_A_tu_viet}")
if dinh_thuc_A_tu_viet != 0:
    nghiem_tu_viet = np.linalg.solve(A, B)
    print("Nghiệm của hệ ptrình là:")
    print(f"x = {nghiem_tu_viet[0]}, y = {nghiem_tu_viet[1]}, z = {nghiem_tu_viet[2]}")
else:
    print("Hệ ptrình không có nghiệm duy nhất")


Định thức của ma trận hệ số (A) là: -8.881784197001244e-16
Nghiệm của hệ ptrình là:
x = 1.0, y = -1.25, z = -1.5


In [54]:
import sympy as sp
TG = sp.Matrix([[1, 0, 1],[4, 3, 1], [2, 2, 1]])
KQ = 1/2*TG.det()
print ("Kết quả diện tích tam giác là: ",KQ)

Kết quả diện tích tam giác là:  1.50000000000000


In [55]:
import sympy as sp
M = sp.Matrix([[0,4,1,1],[4,0,0,1],[3,5,2,1],[2,2,5,1]])
M.det()
KQ = 1/6*M.det()
print ("Thể tích của tứ diện là: ",KQ)

Thể tích của tứ diện là:  -12.0000000000000


In [56]:
import sympy as sp
x, y, z = sp.symbols('x y z')
MP = sp.Matrix([
    [x, y, z, 1],
    [-1, 3, 2, 1],
    [0, 1, 0, 1],
    [-2, 0, 1, 1]])
dinh_thuc = MP.det()
phuong_trinh_mat_phang = dinh_thuc
print("Định thức của ma trận MP là:", dinh_thuc)
print("Phương trình mặt phẳng là:", phuong_trinh_mat_phang)

Định thức của ma trận MP là: -4*x + 3*y - 5*z - 3
Phương trình mặt phẳng là: -4*x + 3*y - 5*z - 3


Câu 1 BTVN

a/

In [57]:
import numpy as np
def lay_ma_tran_he_so_kep(ma_tran):
    n = len(ma_tran)
    ma_tran_he_so_kep = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            phu_hop = np.delete(np.delete(ma_tran, i, axis=0), j, axis=1)
            ma_tran_he_so_kep[i][j] = ((-1) ** (i + j)) * np.linalg.det(phu_hop)

    return ma_tran_he_so_kep
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
ma_tran_he_so_kep = lay_ma_tran_he_so_kep(A)
print("Ma trận A:")
print(A)
print("\nMa trận hệ số kép của A:")
print(ma_tran_he_so_kep)

Ma trận A:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Ma trận hệ số kép của A:
[[-24.  20.  -5.]
 [ 18. -15.   4.]
 [  5.  -4.   1.]]


b/

In [58]:
import numpy as np
def lay_ma_tran_he_so_kep(ma_tran):
    n = len(ma_tran)
    ma_tran_he_so_kep = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            phu_hop = np.delete(np.delete(ma_tran, i, axis=0), j, axis=1)
            ma_tran_he_so_kep[i][j] = ((-1) ** (i + j)) * np.linalg.det(phu_hop)
    return ma_tran_he_so_kep
def lay_ma_tran_lien_hop(ma_tran):
    ma_tran_he_so_kep = lay_ma_tran_he_so_kep(ma_tran)
    ma_tran_lien_hop = np.transpose(ma_tran_he_so_kep)
    return ma_tran_lien_hop
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
ma_tran_lien_hop = lay_ma_tran_lien_hop(A)
print("Ma trận A:")
print(A)
print("\nMa trận liên hợp của A:")
print(ma_tran_lien_hop)

Ma trận A:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Ma trận liên hợp của A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


Câu 2(BTVN)

In [41]:
import sympy as sp
def phuong_trinh_duong_tron(ba_diem):
    x, y = sp.symbols('x y')
    x1, y1 = ba_diem[0]
    x2, y2 = ba_diem[1]
    x3, y3 = ba_diem[2]
    ma_tran = sp.Matrix([
        [x**2 + y**2, x, y, 1],
        [x1**2 + y1**2, x1, y1, 1],
        [x2**2 + y2**2, x2, y2, 1],
        [x3**2 + y3**2, x3, y3, 1]])
    dinh_thuc = ma_tran.det()
    phuong_trinh = sp.Eq(dinh_thuc, 0)
    return phuong_trinh
ba_diem = [(1, 2), (3, 4), (5, 6)]
phuong_trinh = phuong_trinh_duong_tron(ba_diem)
print("Ptrình đường tròn đi qua 3 điểm {} là:".format(ba_diem))
print(phuong_trinh)

Ptrình đường tròn đi qua 3 điểm [(1, 2), (3, 4), (5, 6)] là:
Eq(32*x - 32*y + 32, 0)
