In [ ]:
import numpy as np
from numpy.linalg import det, inv, eig, norm, solve
import math

# Câu 1: Phép toán cơ bản trên vector và ma trận
print("\n### Câu 1 ###")
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])
sum_AB = A + B
scalar_mult = 2 * A + 3 * B
dot_product = np.dot(A, B)
norm_A = np.linalg.norm(A)
norm_B = np.linalg.norm(B)
cos_theta = dot_product / (norm_A * norm_B)
angle_deg = math.degrees(math.acos(cos_theta))
angle_deg = round(angle_deg, 3)
CC_T = np.dot(C, C.T)
print("a) A + B =", sum_AB)
print("   2A + 3B =", scalar_mult)
print("b) Tích vô hướng A · B =", dot_product)
print("   Góc giữa hai vector =", angle_deg, "độ")
print("c) Tích ma trận C · Cᵀ =\n", CC_T)

#---------------------------------------------------------------------------------------------------

# Câu 2: Nhân ma trận, định thức và hạng ma trận
print("\n### Câu 2 ###")
M = np.array([[-1, 2, -1],
              [0, 4, 2],
              [-1, 0, 1]])
N = np.array([[1, 1, 4, 5, 2],
              [3, 2, 0, 1, 0],
              [2, -1, -3, 1, 4]])

# a) Tính tích ma trận MN (không thực hiện được do M là 3x3 và N là 3x5)
# Để nhân được, số cột của M phải bằng số hàng của N.

# b) Tính định thức của ma trận M
det_M = det(M)
print(f"Định thức của M: {det_M}")
if det_M != 0:
    print("Ma trận M khả nghịch.\n")
else:
    print("Ma trận M không khả nghịch.\n")

# c) Tính hạng của ma trận N
rank_N = np.linalg.matrix_rank(N)
print(f"Hạng của N: {rank_N}\n")

#---------------------------------------------------------------------------------------------------

# Câu 3: Nghịch đảo ma trận và giải hệ phương trình
print("\n### Câu 3 ###")
P = np.array([[3, -1, 0, 2],
              [1, 2, -2, 1],
              [0, 1, 5, -1],
              [2, 0, 1, 4]])

# Hệ phương trình:
# 3x - y + 2w = 6
# x + 2y - 2z + w = 3
# y + 5z - w = -2
# 2x + z + 4w = 7

# a) Tìm ma trận nghịch đảo của P
try:
    P_inv = inv(P)
    print(f"Ma trận nghịch đảo của P:\n{P_inv}\n")
except np.linalg.LinAlgError:
    print("Ma trận P không khả nghịch.\n")

# b) Giải hệ phương trình
b3 = np.array([6, 3, -2, 7])
try:
    x3 = solve(P, b3)
    print(f"Nghiệm của hệ phương trình (x, y, z, w): {tuple(x3)}\n")
except np.linalg.LinAlgError:
    print("Hệ phương trình không có nghiệm duy nhất.\n")

# c) Kiểm tra nghiệm
# So sánh P * x3 với b3
verification = P @ x3
print(f"Kiểm tra lại nghiệm (P * x): {verification}")
print(f"Vector kết quả b: {b3}")
print(f"So sánh P*x và b: {np.allclose(verification, b3)}\n") # allclose để so sánh số thực

#---------------------------------------------------------------------------------------------------

# Câu 4: Giá trị riêng, vector riêng và chuẩn hóa
print("\n### Câu 4 ###")
# Define the matrix Q
Q = np.array([
    [5, -2, 1],
    [0, 3, -1],
    [2, 0, 4]
])

print("Ma trận Q:")
print(Q)
print("-" * 30)

# a) Find the eigenvalues of Q
# np.linalg.eig returns a tuple (eigenvalues, eigenvectors)
eigenvalues, eigenvectors = np.linalg.eig(Q)

print("a) Các giá trị riêng của Q:")
# Eigenvalues can be complex, let's print them nicely rounded
print("Giá trị riêng (làm tròn đến 4 chữ số thập phân):")
for i, val in enumerate(eigenvalues):
    print(f"  λ{i+1}: {val:.4f}")

print("-" * 30)

# b) Find the eigenvectors corresponding to the eigenvalues
# Eigenvectors are returned as columns of the 'eigenvectors' matrix
print("b) Các vector riêng tương ứng với các giá trị riêng:")
# We use .T to iterate through eigenvectors as columns
for i, vec in enumerate(eigenvectors.T):
    print(f"  Vector riêng v{i+1} (tương ứng với λ{i+1:.4f}):")
    print(f"    {vec}")

print("-" * 30)

# c) Normalize all eigenvectors (length equal to 1)
print("c) Các vector riêng đã chuẩn hóa (độ dài bằng 1):")
normalized_eigenvectors = []
for i, vec in enumerate(eigenvectors.T):
    norm = np.linalg.norm(vec) # Calculate the L2 norm (length) of the vector
    normalized_vec = vec / norm
    normalized_eigenvectors.append(normalized_vec)
    print(f"  Vector riêng chuẩn hóa v{i+1}_normalized:")
    print(f"    {normalized_vec}")
    print(f"    Kiểm tra độ dài: {np.linalg.norm(normalized_vec):.4f}") # Verify the length is 1

print("-" * 30)#---------------------------------------------------------------------------------------------------

# Câu 5: Ứng dụng thực tế - Hệ phương trình và phân tích
print("\n### Câu 5 ###")
R = np.array([
    [4, -1, 2],
    [1, 3, -2],
    [0, 2, 5]
])
b = np.array([12, 5, 9])
x = np.linalg.solve(R, b)
print("a) Nghiệm của hệ Rx = b là:")
print(np.round(x, 3))
try:
    R_inv = np.linalg.inv(R)
    x_inv = np.dot(R_inv, b)
    print("\nb) Ma trận R khả nghịch.")
    print("   Nghiệm tìm bằng R⁻¹ * b là:")
    print(np.round(x_inv, 3))
    print("   So sánh với np.linalg.solve:", np.allclose(x, x_inv))
except np.linalg.LinAlgError:
    print("\nb) Ma trận R không khả nghịch.")
fro_norm = np.linalg.norm(R, 'fro')
print("\nc) Chuẩn Frobenius của ma trận R là:", round(fro_norm, 3))


### Câu 1 ###
a) A + B = [2 3 1 6]
   2A + 3B = [ 3 11  2 14]
b) Tích vô hướng A · B = -5
   Góc giữa hai vector = 99.594 độ
c) Tích ma trận C · Cᵀ =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]

### Câu 2 ###
Định thức của M: -12.0
Ma trận M khả nghịch.

Hạng của N: 3


### Câu 3 ###
Ma trận nghịch đảo của P:
[[ 0.43220339  0.16101695  0.11016949 -0.22881356]
 [-0.12711864  0.36440678  0.1440678   0.00847458]
 [-0.01694915 -0.08474576  0.15254237  0.06779661]
 [-0.21186441 -0.05932203 -0.09322034  0.34745763]]

Nghiệm của hệ phương trình (x, y, z, w): (np.float64(1.2542372881355932), np.float64(0.1016949152542373), np.float64(-0.18644067796610164), np.float64(1.169491525423729))

Kiểm tra lại nghiệm (P * x): [ 6.  3. -2.  7.]
Vector kết quả b: [ 6  3 -2  7]
So sánh P*x và b: True


### Câu 4 ###
Ma trận Q:
[[ 5 -2  1]
 [ 0  3 -1]
 [ 2  0  4]]
------------------------------
a) Các giá trị riêng của Q:
Giá trị riêng (làm tròn đến 4 chữ số thập phân):
  λ1: 6.3553+0.0000j
  λ2: 2.8223+1.0773j
